---
type: l2leaf

generate_cv_tags:
  device_tags:
    - name: Access-Pod
      data_path: mlag_configuration.domain_id
    - name: Campus-Pod
      value: Campus A
    - name: Campus
      value: Cleveland
    - name: Role
      value: Leaf
